// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: import_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteImportJob = `-- name: DeleteImportJob :exec
DELETE FROM import_jobs WHERE id = $1
`

func (q *Queries) DeleteImportJob(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteImportJob, id)
	return err
}

const getImportJobByID = `-- name: GetImportJobByID :one
SELECT id, filename, input_type, status, progress, result, error_message,
  created_at, started_at, completed_at
FROM import_jobs
WHERE id = $1
`

func (q *Queries) GetImportJobByID(ctx context.Context, id string) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobByID, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.InputType,
		&i.Status,
		&i.Progress,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertImportJob = `-- name: InsertImportJob :one
INSERT INTO import_jobs (
  id, filename, input_type, status, progress, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, filename, input_type, status, progress, result, error_message,
  created_at, started_at, completed_at
`

type InsertImportJobParams struct {
	ID        string
	Filename  pgtype.Text
	InputType string
	Status    string
	Progress  int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertImportJob(ctx context.Context, arg InsertImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, insertImportJob,
		arg.ID,
		arg.Filename,
		arg.InputType,
		arg.Status,
		arg.Progress,
		arg.CreatedAt,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.InputType,
		&i.Status,
		&i.Progress,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateImportJobStatus = `-- name: UpdateImportJobStatus :exec
UPDATE import_jobs SET
  status = $2,
  progress = $3,
  started_at = $4,
  completed_at = $5,
  error_message = $6,
  result = $7
WHERE id = $1
`

type UpdateImportJobStatusParams struct {
	ID          string
	Status      string
	Progress    int32
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	ErrorMessage pgtype.Text
	Result      []byte
}

func (q *Queries) UpdateImportJobStatus(ctx context.Context, arg UpdateImportJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateImportJobStatus,
		arg.ID,
		arg.Status,
		arg.Progress,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.Result,
	)
	return err
}
