// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppSetting struct {
	Key       string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type ExportJob struct {
	ID                string
	PaperID           string
	PaperTitle        string
	Format            string
	Variant           string
	Status            string
	Progress          int32
	DownloadPath      pgtype.Text
	ErrorMessage      pgtype.Text
	CreatedAt         pgtype.Timestamptz
	StartedAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	CancelRequestedAt pgtype.Timestamptz
}

type Image struct {
	ID            string
	Filename      string
	Mime          string
	SizeBytes     int64
	Width         int32
	Height        int32
	StoragePath   string
	ThumbnailPath string
	Description   pgtype.Text
	ParentImageID pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type ImageTag struct {
	ImageID string
	TagID   string
}

type Paper struct {
	ID           string
	Title        string
	Subtitle     pgtype.Text
	SchoolName   pgtype.Text
	ExamName     pgtype.Text
	Subject      pgtype.Text
	DurationMin  pgtype.Int4
	TotalScore   pgtype.Numeric
	Description  pgtype.Text
	Status       string
	Instructions pgtype.Text
	FooterText   pgtype.Text
	HeaderJson   []byte
	LayoutJson   []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type PaperItem struct {
	ID            string
	PaperID       string
	ProblemID     string
	OrderIndex    int32
	Score         pgtype.Numeric
	ImagePosition pgtype.Text
	BlankLines    int32
}

type Problem struct {
	ID              string
	Code            string
	Latex           string
	AnswerLatex     pgtype.Text
	SolutionLatex   pgtype.Text
	ProblemType     string
	Difficulty      string
	SubjectiveScore pgtype.Numeric
	Subject         pgtype.Text
	Grade           pgtype.Text
	Source          pgtype.Text
	Notes           pgtype.Text
	SearchTsv       interface{}
	FormulaTokens   pgtype.Text
	FormulaTsv      interface{}
	Version         int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type ProblemCodeCounter struct {
	Year          int32
	CurrentSerial int32
	UpdatedAt     pgtype.Timestamptz
}

type ProblemImage struct {
	ProblemID  string
	ImageID    string
	OrderIndex int32
}

type ProblemTag struct {
	ProblemID string
	TagID     string
}

type ProblemVersion struct {
	ID        string
	ProblemID string
	Version   int32
	Snapshot  []byte
	CreatedAt pgtype.Timestamptz
}

type SavedSearch struct {
	ID        string
	Name      string
	Query     pgtype.Text
	Filters   []byte
	CreatedAt pgtype.Timestamptz
}

type SearchHistory struct {
	ID          string
	Query       string
	Filters     []byte
	ResultCount int32
	CreatedAt   pgtype.Timestamptz
}

type Tag struct {
	ID          string
	Name        string
	Category    string
	Color       string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ImportJob struct {
	ID           string
	Filename     pgtype.Text
	InputType    string
	Status       string
	Progress     int32
	Result       []byte
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
}
